version: '2'
services:
    bpremiser:
        build:
            context: ./PREMISer/
            args:
                PORT: "8910"
                WORKERS: "${NUM_WORKERS}"
                TIMEOUT: "${TIMEOUT}"
        expose:
            - "8910"
        environment:
             - PREMISER_CONFIG=/code/config.py
    premiser:
        build:
            context: ./loadbalancer/
            args:
                UPSTREAM: "http://bpremiser:8910"
                LISTEN: "8910"
                REFRESH: "${REFRESH}"
                TIMEOUT: "${TIMEOUT}"
                MAX_FSIZE: "${MAX_FSIZE}"
        expose:
            - "8910"
        depends_on:
            - bpremiser 
    bmaterialsuite_endpoint:
        build:
            context: ./ldr_materialsuite_endpoint/
            args:
                PORT: "8911"
                WORKERS: "${NUM_WORKERS}"
                TIMEOUT: "${TIMEOUT}"
        expose:
            - "8911"
        environment:
             - MATERIALSUITE_ENDPOINT_CONFIG=/code/config.py
        volumes:
            - ${LTS_PATH}:/lts 
            - ${PREMIS_PATH}:/premis
    materialsuite_endpoint:
        build:
            context: ./loadbalancer/
            args:
                UPSTREAM: "http://bmaterialsuite_endpoint:8911"
                LISTEN: "8911"
                REFRESH: "${REFRESH}"
                TIMEOUT: "${TIMEOUT}"
                MAX_FSIZE: "${MAX_FSIZE}"
        expose:
            - "8911"
    bidnest:
        build:
            context: ./idnest/
            args:
                PORT: "8912"
                WORKERS: "${NUM_WORKERS}"
                TIMEOUT: "30"
        expose:
            - "8912"
        depends_on:
            - mongo
        environment:
            - IDNEST_CONFIG=/code/config.py
    idnest:
        build:
            context: ./loadbalancer/
            args:
                UPSTREAM: "http://bidnest:8912"
                LISTEN: "8912"
                REFRESH: "${REFRESH}"
                TIMEOUT: "${TIMEOUT}"
                MAX_FSIZE: "${MAX_FSIZE}"
        expose:
            - "8912"
        depends_on:
            - bidnest
    bingress:
        build:
            context: ./ldr_ingress/
            args:
                PORT: "8913"
                WORKERS: "${NUM_WORKERS}"
                TIMEOUT: "${TIMEOUT}"
        depends_on:
            - idnest
            - premiser
            - materialsuite_endpoint
        environment:
            - INGRESS_CONFIG=/code/config.py
    ingress:
        build: 
            context: ./loadbalancer/
            args:
                UPSTREAM: "http://bingress:8913"
                LISTEN: "8913"
                REFRESH: "${REFRESH}"
                TIMEOUT: "${TIMEOUT}"
                MAX_FSIZE: "${MAX_FSIZE}"
        depends_on:
            - bingress
    mongo:
        image: "mongo"
        expose:
            - "27017"
        volumes:
            - ${DB_PATH}:/data/db
    bunifier:
        build:
            context: ./unifier/
        expose: 
            - "8888"
        depends_on:
            - idnest
            - ingress
            - materialsuite_endpoint
            - premiser
    unifier:
        build:
            context: ./unifier_loadbalancer/
        expose:
            - "8888"
        ports: 
            - "${UNIFIER_EXTERNAL_PORT}:8888"
        depends_on:
            - bunifier
