version: '2'
services:
    bpremiser:
        build:
            context: ./PREMISer/
            args:
                PORT: "8910"
        expose:
            - "8910"
        environment:
             - PREMISER_CONFIG=/code/config.py
    premiser:
        build:
            context: ./premiser_loadbalancer/
        expose:
            - "8910"
        depends_on:
            - bpremiser 
    bmaterialsuite_endpoint:
        build:
            context: ./ldr_materialsuite_endpoint/
            args:
                PORT: "8911"
        expose:
            - "8911"
        environment:
             - MATERIALSUITE_ENDPOINT_CONFIG=/code/config.py
        volumes:
            - ${LTS_PATH}:/lts 
            - ${PREMIS_PATH}:/premis
    materialsuite_endpoint:
        build:
            context: ./materialsuite_endpoint_loadbalancer/
        expose:
            - "8911"
        ports:
            - "${MATERIALSUITE_EXTERNAL_PORT}:8911"
    bidnest:
        build:
            context: ./idnest/
            args:
                PORT: "8912"
        expose:
            - "8912"
        depends_on:
            - mongo
        environment:
            - IDNEST_CONFIG=/code/config.py
    idnest:
        build:
            context: ./idnest_loadbalancer/
        expose:
            - "8912"
        ports:
            - "${ACCS_EXTERNAL_PORT}:8912"
        depends_on:
            - bidnest
    bingress:
        build:
            context: ./ldr_ingress/
            args:
                PORT: "8913"
        depends_on:
            - idnest
            - premiser
            - materialsuite_endpoint
        environment:
            - INGRESS_CONFIG=/code/config.py
    ingress:
        build: 
            context: ./ingress_loadbalancer/
        ports:
            - "${INGRESS_EXTERNAL_PORT}:8080"
        depends_on:
            - bingress
    mongo:
        image: "mongo"
        expose:
            - "27017"
        volumes:
            - ${DB_PATH}:/data/db
